### ISSUE TITLE
changed symbols in kernels >= 4.17 causes panic in sensor

### ISSUE THREAD

**Issue by dustin-decker** [capsule8/capsule8#225]
### Is this a bug report or a feature request?

- [x ] bug
- [ ] feature

### What is the current behavior?

Sensor example fails to start, panicking because `sys_execve` is not present:

```bash
➜  capsule8 git:(master) sudo ./bin/sensor
I0701 19:42:36.917941   24008 version.go:76] Starting sensor (v0.15.0-alpha+d3fbc4e)
I0701 19:42:36.918227   24008 sensor.go:134] x86_64 dustin Linux 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018
F0701 19:42:37.110351   24008 process.go:573] Couldn't register event sys_execve: Kernel symbol not found: sys_execve
goroutine 1 [running]:
github.com/capsule8/capsule8/vendor/github.com/golang/glog.stacks(0xc420198f00, 0xc420aae270, 0x76, 0xc7)
	/home/dustin/go/src/github.com/capsule8/capsule8/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/capsule8/capsule8/vendor/github.com/golang/glog.(*loggingT).output(0xcf9c40, 0xc400000003, 0xc4200bdce0, 0xca2e2a, 0xa, 0x23d, 0x0)
	/home/dustin/go/src/github.com/capsule8/capsule8/vendor/github.com/golang/glog/glog.go:720 +0x32d
github.com/capsule8/capsule8/vendor/github.com/golang/glog.(*loggingT).printf(0xcf9c40, 0x3, 0x9d6c09, 0x1e, 0xc420061ac0, 0x2, 0x2)
	/home/dustin/go/src/github.com/capsule8/capsule8/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/capsule8/capsule8/vendor/github.com/golang/glog.Fatalf(0x9d6c09, 0x1e, 0xc420061ac0, 0x2, 0x2)
	/home/dustin/go/src/github.com/capsule8/capsule8/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/capsule8/capsule8/pkg/sensor.NewProcessInfoCache(0xc4201907e0, 0xc420a5c900)
	/home/dustin/go/src/github.com/capsule8/capsule8/pkg/sensor/process.go:573 +0xabd
github.com/capsule8/capsule8/pkg/sensor.(*Sensor).Start(0xc4201907e0, 0x0, 0x0)
	/home/dustin/go/src/github.com/capsule8/capsule8/pkg/sensor/sensor.go:183 +0x2d9
github.com/capsule8/capsule8/pkg/sensor.Main()
	/home/dustin/go/src/github.com/capsule8/capsule8/pkg/sensor/main.go:37 +0xba
main.main()
	/home/dustin/go/src/github.com/capsule8/capsule8/cmd/sensor/main.go:32 +0x6e
```

### What is the desired behavior?

Sensor should start without kprobe insertion failures

### What version of Capsule8 are you using?

`v0.15.0-alpha+d3fbc4e`

### What kind of environment is this in?

Linux x86_64

What linux distribution are you running?

Fedora 28

### For bugs: can you share logs?

Anything you need

### Other Information

After changing logging from fatal to warning, I found additional symbols missing:

```bash
➜  capsule8 git:(master) sudo ./bin/sensor
I0701 19:44:38.394843   24789 version.go:76] Starting sensor (v0.15.0-alpha+d3fbc4e-dirty)
I0701 19:44:38.395081   24789 sensor.go:134] x86_64 lolbox Linux 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018
W0701 19:44:38.646534   24789 process.go:576] Couldn't register event sys_execve: Kernel symbol not found: sys_execve
W0701 19:44:38.780182   24789 docker_monitor.go:114] Could not register Docker monitor sys_renameat kprobe: Kernel symbol not found: sys_renameat
W0701 19:44:38.780197   24789 docker_monitor.go:123] Could not register Docker monitor sys_unlinkat kprobe: Kernel symbol not found: sys_unlinkat
```

Had to run with kernel lockdown disabled (sysrq+x shortcut) because it's a UEFI system. I don't think it's in mainline still, but Fedora has been using the patch for a while.

I believe it ran under `4.16.15-300.fc28.x86_64` but I didn't see any obvious changes in the kernel `.config` that would have caused this. I'd be happy to provide configs, kallsyms, or whatever might help shed light on this.

**Comment by dustin-decker** [comment]
`sys_execve` IS present in `4.16.15-300.fc28.x86_64`:

```bash
➜  linux git:(29dcea88) ✗ grep sys_execve /usr/src/kernels/4.16.15-300.fc28.x86_64/System.map 
ffffffff8128dc40 T sys_execve
ffffffff8128dc80 T sys_execveat
ffffffff8128dcd0 T compat_sys_execve
ffffffff8128dd10 T compat_sys_execveat
```

I just compiled vanilla kernel v4.17 using `4.16.15-300.fc28.x86_64`'s `.config` updated with `make oldconfig` and the symbol is not present in `System.map`....

I'm pretty sure now that the missing symbol is from an upstream kernel change but haven't tracked down exactly which change it was.

**Comment by dustin-decker** [comment]
`SyS_connect` seems to be missing as well:

```bash
➜  capsule8 git:(master) ✗ sudo ./bin/telemetry                 
code:2 message:"Couldn't register kprobe on SyS_connect entry [sin_addr=+4(%si):u32 sin_family=+0(%si):u16 sin_port=+2(%si):u16]: Kernel symbol not found: SyS_connect" 
code:2 message:"Invalid filter expression for syscall enter filter: Type mismatch (uint64 vs. int64)" 
...
```

**Comment by dustin-decker** [comment]
The syscalls seem to be available under a symbol with an architecture prefix, introduced by https://github.com/torvalds/linux/commit/d5a00528b58cdb2c71206e18bd021e34c4eab878

So, `sys_execve` becomes `__x64_sys_execve`. I tried updating the kprobe address, but the filename and commandline variables come back wrong, so I think it's probably a different structure than before.

**Comment by orangematt** [comment]
Thanks for tracking this down, Dustin. That naming convention change is definitely going to wreak some havoc on the sensor. There'll be a bit more than just the `execve` and `connect` syscalls that'll need to be updated. Unless there's also been some change to the syscall ABI, the filename and argv arguments shouldn't be affected. Sounds like more investigation will be necessary there. If `execve` is affected, other syscalls will be as well.

**Comment by kallsyms** [comment]
With https://github.com/capsule8/capsule8/pull/229 merged, this should be fully fixed. Closing.
